### ISSUE TITLE
How to disable?

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz-hints#1]
It comes pre-bundled with Blitz, how do you disable it if you don't want to use the functionality?
It causes many writes for our site, and optimizing the queries is not on the dev-agenda anytime soon

**Comment by john-henry** [comment]
https://github.com/putyourlightson/craft-blitz/blob/develop/src/config.php#L26

`'hintsEnabled' => false,`

in your blitz config would do it
