### ISSUE TITLE
Add last url that triggered the hint

### ISSUE THREAD

**Issue by webrgp** [putyourlightson/craft-blitz-hints#2]
It would be nice to have a "globe" icon at the end of the hint with the last occurrence that triggered the hint. That's would be specially helpful to new devs coming into existing projects and not super familiar with the content and its structure.

**Comment by bencroker** [comment]
I’m not quite following. What exactly would the globe icon do or indicate?

**Comment by bencroker** [comment]
Ah I just noticed the title indicates the “last url that triggered the hint”. Thanks for the suggestion, I’ll look into whether this is feasible to add.

**Comment by bencroker** [comment]
Rather than add URLs, I’ve added a template stack trace in [1.2.0](https://github.com/putyourlightson/craft-blitz-hints/releases/tag/1.2.0).

![screenshot-aQ9JKMZX@2x](https://github.com/putyourlightson/craft-blitz-hints/assets/57572400/ab51884f-bc06-4810-bf95-838d47b00de9)

**Comment by webrgp** [comment]
That's nice, but I the reason I would rather have the last url that triggers the hint is so I could quickly see which page I can use to validate fixes.

My current DX flow is to:

1. See the hint
2. Look for the template and figure it out an route that trigger the hint (so I can validate the fix later)
3. Apply fix
4. "Clear all"
5. Visit the route that trigger the hint and see if that generates the hint again, or a different one.
6. Repeat

My dream DX scenario would looks like the image below, where the "globe" would be a link to the route that triggered the hint (for quick validation), and (or) the "refresh" button that would re-run the validation behind the scenes and validate / clear the specific hint hint.

![blitz-mock](https://github.com/putyourlightson/craft-blitz-hints/assets/994788/d66e2dea-6134-4535-abcf-c56610ca8604)

Right now I constantly clearing the hints, refresh multiple FE routes, go back and refresh cp page to see what else needs fixing, again and again.

Maybe the way I've been using isn't the correct one, in which case feel free to enlighten me :grin:

**Comment by bencroker** [comment]
That makes sense to me. With the changes coming in Craft 5, however, this is going to be a non-issue, as applying lazy eager-loading by adding `.eagerly()` to element queries is going to be a quick fix. I’ll revisit this when Craft 5 is out, but thanks for the suggestion!

**Comment by webrgp** [comment]
That makes sense. As always, thanks for this awesome plugin!
